const SkillsList = [
  [
    { name: "HTML5", lev: 80 },
    { name: "CSS3", lev: 80 },
    { name: "JavaScript", lev: 80 },
    { name: "React", lev: 75 },
    { name: "Git", lev: 70 },
    { name: "GitHub", lev: 70 },
    { name: "Node.js", lev: 70 },
    { name: "Express.js", lev: 50 },
    { name: "Next.js", lev: 50 },
    { name: "PostgreSQL", lev: 50 },
    { name: "Postman", lev: 50 },
    { name: "Tachyons", lev: 40 },
    { name: "Bootstrap", lev: 40 },
    { name: "Sass", lev: 30 },
    { name: "Python", lev: 20 },
  ],
  [
    { name: "VS Code", lev: 90 },
    { name: "Heroku", lev: 60 },
    { name: "DBeaver", lev: 60 },
    { name: "Office Package", lev: 95 },
    { name: "YouTrack", lev: 90 },
    { name: "Asana", lev: 80 },
    { name: "Adobe  XD", lev: 70 },
    { name: "Slack", lev: 85 },
    { name: "Miro", lev: 75 },
    { name: "Zoom", lev: 90 },
  ],
  [
    { name: "Problem Solving", lev: 95 },
    { name: "Agile Methodology", lev: 85 },
    { name: "Creative Thinking", lev: 90 },
    { name: "Analytical Skills", lev: 90 },
    { name: "Goals Orientation", lev: 95 },
    { name: "Time Management", lev: 85 },
    { name: "Communication", lev: 75 },
    { name: "Team Work", lev: 75 },
  ],
  [
    { name: "Making delicious foods", lev: 98 },
    { name: "Cuddling dogs", lev: 100 },
    { name: "Hiking mountains", lev: 85 },
    { name: "Drinking coffee", lev: 80 },
  ],
];

export default SkillsList;
